version: '3.8'

services:
  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
